name: core_util
description: core util package.
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.0.10+1
  intl: 0.20.2
  shimmer: 3.0.0

dev_dependencies:
  flutter_lints: 3.0.1